### ISSUE TITLE
多次选择图片重复

### ISSUE THREAD

**Issue by yirenyishi** [Vanish136/NineGridView#1]
我分两次选择图片，mNineGridView.addDataList(resultList); 并没有清空之前选择好的数据，

**Comment by Vanish136** [comment]
@yirenyishi 
如果你希望多次选择的时候，每次都清空上一次数据，应该调用setDataList(resultList)方法。

**Comment by yirenyishi** [comment]
恩，刚才看你的源码的时候，看到了，没注意方法名。
