### ISSUE TITLE
作者你好，我用此库做图片展示，当只有2两图片的时候，图片会小很多，请问我要怎么做

### ISSUE THREAD

**Issue by yonglf** [Vanish136/NineGridView#10]

**Comment by yonglf** [comment]
<img width="298" alt="WX20200424-120425@2x" src="https://user-images.githubusercontent.com/26603973/80173967-f9bb4b00-8623-11ea-9bd7-1f96930cba7b.png">
<img width="313" alt="WX20200424-120452@2x" src="https://user-images.githubusercontent.com/26603973/80173978-fd4ed200-8623-11ea-874c-7b3fd59537f1.png">

**Comment by Vanish136** [comment]
方便贴出你的布局文件吗

**Comment by yonglf** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@android:color/white"
    android:padding="15dp">

    <RelativeLayout
        android:id="@+id/rl_user_info"
        android:layout_width="match_parent"
        android:layout_height="50dp">

        <ImageView
            android:id="@+id/iv_avatar"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:layout_marginRight="10dp"
            android:src="@mipmap/ic_launcher_round" />

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_centerVertical="true"
            android:layout_toRightOf="@id/iv_avatar"
            android:orientation="vertical">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_weight="1">

                <com.schhtc.company.project.view.DrawableTextView
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    android:drawablePadding="6dp"
                    android:gravity="center"
                    android:text="@string/app_name"
                    android:textColor="@color/color_1A1A1A"
                    android:textSize="14sp"
                    app:dt_right_drawable="@mipmap/icon_girl"
                    app:dt_right_height="11dp"
                    app:dt_right_width="11dp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    android:layout_alignParentRight="true"
                    android:gravity="center"
                    android:text="00-00 00:00"
                    android:textColor="@color/color_1A1A1A"
                    android:textSize="12sp" />
            </RelativeLayout>

            <com.schhtc.company.project.view.DrawableTextView
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:drawablePadding="6dp"
                android:gravity="center"
                android:text="设计师"
                android:textColor="@color/color_999999"
                android:textSize="14sp"
                app:dt_left_drawable="@mipmap/icon_zhiwei_type"
                app:dt_left_height="12dp"
                app:dt_left_width="12dp" />

        </LinearLayout>

    </RelativeLayout>

    <TextView
        android:id="@+id/tv_content"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/rl_user_info"
        android:layout_marginLeft="50dp"
        android:layout_marginTop="5dp"
        android:text="说好的回家清水煮白菜呢？对不起，实在没忍住[社会社会~"
        android:textColor="@color/color_1A1A1A"
        android:textSize="16sp" />

    <com.lwkandroid.widget.ninegridview.NineGridView
        android:id="@+id/nine_grid_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/tv_content"
        android:layout_marginLeft="50dp"
        android:layout_marginTop="10dp" />

    <com.xxxxx.view.DrawableTextView
        android:id="@+id/tv_comment"
        android:layout_width="wrap_content"
        android:layout_height="43dp"
        android:layout_below="@id/nine_grid_view"
        android:layout_marginLeft="50dp"
        android:drawablePadding="10dp"
        android:gravity="center"
        android:text="0"
        android:textColor="@color/color_1A1A1A"
        android:textSize="14sp"
        app:dt_left_drawable="@mipmap/icon_work_log_comment"
        app:dt_left_height="13dp"
        app:dt_left_width="13dp" />

    <com.xxxxx.view.DrawableTextView
        android:id="@+id/tv_zan"
        android:layout_width="wrap_content"
        android:layout_height="43dp"
        android:layout_below="@id/nine_grid_view"
        android:layout_marginLeft="50dp"
        android:layout_toRightOf="@id/tv_comment"
        android:drawablePadding="10dp"
        android:gravity="center"
        android:text="0"
        android:textColor="@color/color_1A1A1A"
        android:textSize="14sp"
        app:dt_left_drawable="@mipmap/icon_work_log_zan"
        app:dt_left_height="13dp"
        app:dt_left_width="13dp" />

    <include
        layout="@layout/public_line"
        android:layout_width="match_parent"
        android:layout_height="0.5dp"
        android:layout_below="@id/tv_comment" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:layout_below="@+id/lineView"
        android:layout_marginLeft="50dp"
        android:layout_marginTop="15dp"
        android:background="@drawable/work_log_comment_edit_bg"
        android:gravity="center_vertical"
        android:paddingLeft="15dp"
        android:text="@string/work_log_input_comment" />
</RelativeLayout>

**Comment by yonglf** [comment]
布局大概就是这个样子  和朋友圈差不多

**Comment by Vanish136** [comment]
好的 我明白了 我代码里对宽度计算时 当数量小于列数时的计算方式是有问题的 这个我抽空修复一下吧

**Comment by yonglf** [comment]
好的，谢谢大佬

**Comment by Vanish136** [comment]
1.3.0版本已经重构了测量方式，你可以试试

**Comment by yonglf** [comment]
好的  我试试

**Comment by yonglf** [comment]
我刚才升到了1.3.0，2张图的时候还是不对，跟之前是一样的

**Comment by Vanish136** [comment]
嗯？不应该啊  你方便把代码一起贴一下吗？

**Comment by yonglf** [comment]
String url = "https://c-ssl.duitang.com/uploads/item/201503/21/20150321160159_vVxSC.jpeg";

    private List<NineGridBean> getImageInfos() {
        List<NineGridBean> imageInfos = new ArrayList<>();
        for (int i = 0; i < 2; i++) {
            NineGridBean imageInfo = new NineGridBean(url, url);
            imageInfos.add(imageInfo);
        }
        return imageInfos;
    }

**Comment by yonglf** [comment]
@Override
    protected void convert(@NotNull BaseViewHolder baseViewHolder, Object o) {
        NineGridView nine_grid_view = baseViewHolder.getView(R.id.nine_grid_view);
        nine_grid_view.setImageLoader(new GlideImageLoader());
        //设置显示列数，默认3列
        nine_grid_view.setColumnCount(3);
        //设置是否为编辑模式，默认为false
        nine_grid_view.setIsEditMode(false);
        //设置单张图片显示时的尺寸，默认100dp
        nine_grid_view.setSingleImageWidth(SizeUtils.px2dp(ScreenUtils.getScreenWidth()) - 80);
        //设置单张图片显示时的宽高比，默认1.0f
        nine_grid_view.setSingleImageRatio(0.8f);
        //设置最大显示数量，默认9张
        nine_grid_view.setMaxNum(9);
        //设置图片显示间隔大小，默认3dp
        nine_grid_view.setSpcaeSize(5);
//        //设置删除图片
//        nine_grid_view.setIcDeleteResId(R.drawable.ic_delete);
//        //设置删除图片与父视图的大小比例，默认0.25f
//        nine_grid_view.setRatioOfDeleteIcon(0.35f);
//        //设置“+”号的图片
//        nine_grid_view.setIcAddMoreResId(R.drawable.ic_plus);
        nine_grid_view.setDataList(getImageInfos());
        nine_grid_view.setOnItemClickListener(new NineGridView.onItemClickListener() {
            @Override
            public void onNineGirdAddMoreClick(int dValue) {

            }

            @Override
            public void onNineGirdItemClick(int position, NineGridBean gridBean, NineGirdImageContainer imageContainer) {
                ToastUtils.showShort(gridBean.getOriginUrl());
            }

            @Override
            public void onNineGirdItemDeleted(int position, NineGridBean gridBean, NineGirdImageContainer imageContainer) {

            }
        });
    }

**Comment by Vanish136** [comment]
我居然看不出来有什么问题。。
这样吧  我自己试试写个朋友圈的样式模拟下吧

**Comment by yonglf** [comment]
嗯嗯，只有2张图的时候才会这样

**Comment by Vanish136** [comment]
方面的话加个QQ505515031

**Comment by yonglf** [comment]
好的  已经加了

**Comment by yonglf** [comment]
你好  作者   这个问题是  如果根布局是RelativeLayout的话  就会存在这个问题   今天我测试出来了

**Comment by Vanish136** [comment]
@yonglf 好 我有空的时候看看
