### ISSUE TITLE
设置最大数量的图片后，然后选取最大数量照片显示，删除时候，＋号不在显示了

### ISSUE THREAD

**Issue by 13938417646** [Vanish136/NineGridView#11]

**Comment by 13938417646** [comment]
> _No description provided._

使用的是最新版本

**Comment by Vanish136** [comment]
![image](https://user-images.githubusercontent.com/8628073/82869700-4bc3f900-9f61-11ea-9208-978e51e9de99.png)
这个问题已经修复了 参考这个commit
但是最近梯子出问题了 发布不了新版本 着急的话自己clone源码替换吧

**Comment by 13938417646** [comment]
> ![image](https://user-images.githubusercontent.com/8628073/82869700-4bc3f900-9f61-11ea-9208-978e51e9de99.png)
> 这个问题已经修复了 参考这个commit
> 但是最近梯子出问题了 发布不了新版本 着急的话自己clone源码替换吧

好的，本周之内可以发版本么

**Comment by Vanish136** [comment]
不好说啊 看看梯子什么时候恢复

**Comment by 13938417646** [comment]
> 不好说啊 看看梯子什么时候恢复

好的，麻烦老哥发好了，告知一下哈

**Comment by Vanish136** [comment]
1.4.3版本已发布

**Comment by 13938417646** [comment]
> 1.4.3版本已发布

引不进来啊，是需要等待几个小时么?

**Comment by Vanish136** [comment]
1.4.3可以依赖啊 我试过了
