### ISSUE TITLE
你好  作者   这个问题是  如果根布局是RelativeLayout的话  就会存在这个问题   今天我测试出来了

### ISSUE THREAD

**Issue by yonglf** [Vanish136/NineGridView#13]
你好  作者   这个问题是  如果根布局是RelativeLayout的话  就会存在这个问题   今天我测试出来了

_Originally posted by @yonglf in https://github.com/Vanish136/NineGridView/issues/10#issuecomment-647305351_

**Comment by Vanish136** [comment]
@yonglf 我假期的时候复现出来了 确实用RelativeLayout会出现这样的问题 断点看了两次测量过程 第一次是正常的 当自动调整宽度后就有问题 这个问题估计要改掉我内部自动适应宽度的策略 短期内我还暂时抽不出时间来搞  所以暂时先别用这RelativeLayout吧 以后有空了我再看看

**Comment by yonglf** [comment]
> @yonglf 我假期的时候复现出来了 确实用RelativeLayout会出现这样的问题 断点看了两次测量过程 第一次是正常的 当自动调整宽度后就有问题 这个问题估计要改掉我内部自动适应宽度的策略 短期内我还暂时抽不出时间来搞 所以暂时先别用这RelativeLayout吧 以后有空了我再看看

好的，谢谢作者，我现在用的LinearLayout，没有什么问题

**Comment by Vanish136** [comment]
2.0重构后的版本解决了这个问题
但是不兼容1.x版本 请自行评估是否升级
