### ISSUE TITLE
你好，能否将右上角删除icon设置成可替换

### ISSUE THREAD

**Issue by 1900han** [Vanish136/NineGridView#2]

**Comment by Vanish136** [comment]
@1900han 
1.2.2版本的更新了，下面是你需要的方法 
//设置删除图片
mNineGridView.setIcDeleteResId(R.drawable.ic_block_black_24dp);
//设置删除图片与父视图的大小比例，默认0.35f
mNineGridView.setRatioOfDeleteIcon(0.4f);

**Comment by 1900han** [comment]
@Vanish136 
谢谢
