### ISSUE TITLE
要显示的图片数量超过设置的可显示图片数量时，最后一个位置为空白

### ISSUE THREAD

**Issue by jelly-lemon** [Vanish136/NineGridView#3]
比如设置了最多显示6张图片，但是有7张图片时，第六个位置是空白的。可否考虑增加这样的功能：当超过最多能显示的数量时，最后一张图片上面显示“+1”，点击后可往后浏览第七张图片。

**Comment by Vanish136** [comment]
按照你的需求，那需要在源码中，针对显示模式的情况下对最后一张图叠加一层“+”号的图片，你可以自己修改试试
