### ISSUE TITLE
相册选择完返回后 图片没有添加在列表上。

### ISSUE THREAD

**Issue by 1184104588** [Vanish136/NineGridView#4]
方法如下：resultList.add(new NineGridBean(selectListPic.getPath()));
 mNineGridView.addDataList(resultList);
问题： 如题

**Comment by Vanish136** [comment]
设置了图片显示加载器吗？
该控件没有内置图片加载器的，需要自己实现INineGridImageLoader接口设置给它
mNineGridView.setImageLoader(INineGridImageLoader实现类);
