### ISSUE TITLE
空指针问题

### ISSUE THREAD

**Issue by hufu4635** [Vanish136/NineGridView#5]
s是远端字符串地址
`NineGridBean nineGirdData = new NineGridBean(s, s, null);//
`
异常信息如下
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.lwkandroid.widget.ninegridview.NineGridBean.writeToParcel(NineGridBean.java:75)

**Comment by Vanish136** [comment]
你用的哪个版本的？我看了下NineGridView 75行代码对不上啊
请给出完整示例

**Comment by hufu4635** [comment]
> 你用的哪个版本的？我看了下NineGridView 75行代码对不上啊
> 请给出完整示例

用的1.2.2的 新版本1.2.5没有该问题    已解决
