### ISSUE TITLE
setIcAddMoreResId有问题

### ISSUE THREAD

**Issue by dogscar** [Vanish136/NineGridView#6]
设置后setIcAddMoreResId没有马上起效果，需要点击一次选择图片后才生效。

另外 能否设置xml而不只是drawable

**Comment by Vanish136** [comment]
setIcAddMoreResId和setIcDeleteResId都属于初始化的配置，本身并不支持运行时动态修改图片，如果你有这样的需求，可以在修改后手动调用重绘。
icon一般来说都是放在drawable文件夹下的，你是希望加载哪种图？

**Comment by dogscar** [comment]
public void setIcAddMoreResId(int resId)
    {
        this.mIcAddMoreResId = resId;
        //你少了这句代码，不然设置后首次不会成功的，
        mImgAddData.setImageResource(mIcAddMoreResId);
    }



另 能否有 setAddMoreResLayout 加载布局而不是drawable

**Comment by Vanish136** [comment]
你说的对，我下个版本修复这个问题。

另外你说的这个setAddMoreResLayout我不是很理解为什么有这样的需求，你可以克隆我的代码自行修改试试

**Comment by Vanish136** [comment]
1.2.6版本修复了这个问题
