### ISSUE TITLE
删除时候 图片会闪烁

### ISSUE THREAD

**Issue by 13938417646** [Vanish136/NineGridView#9]

**Comment by Vanish136** [comment]
emmm...我能说闪烁在这个控件里出现是无法避免的么 因为删除操作在内部会移除所有child view，然后重新计算宽高、大小等 重新创建child view，所以图片也会重新加载一次，这种机制下手机性能较差就能看到图片闪烁 其实也就是图片重新加载的过程。。 以后有时间我会考虑改掉这个机制

**Comment by 13938417646** [comment]
> emmm...我能说闪烁在这个控件里出现是无法避免的么 因为删除操作在内部会移除所有child view，然后重新计算宽高、大小等 重新创建child view，所以图片也会重新加载一次，这种机制下手机性能较差就能看到图片闪烁 其实也就是图片重新加载的过程。。 以后有时间我会考虑改掉这个机制

嗯，好的。

**Comment by plain-dev** [comment]
@Vanish136 你好，有考虑过通过`RecyclerView`来实现吗

**Comment by Vanish136** [comment]
@plain-dev 想过 但是如果九宫图本来就是用在RecyclerView中展示，类似微博、微信朋友圈那样的场景，就会出现RecyclerView中嵌套RecyclerView，我担心会影响复用机制和性能，所以就用了自定义控件的形式来做。如果你有兴趣可以自己试试。

**Comment by Vanish136** [comment]
@13938417646 1.4.0版本已经实现了内部增量删除、添加ChildView的逻辑，不会再有图片闪动的问题了

**Comment by 13938417646** [comment]
> @13938417646 1.4.0版本已经实现了内部增量删除、添加ChildView的逻辑，不会再有图片闪动的问题了
赞

**Comment by 13938417646** [comment]
> @13938417646 1.4.0版本已经实现了内部增量删除、添加ChildView的逻辑，不会再有图片闪动的问题了

你好，经测试后，发现NineGridBean.originUrl返回的NULL,但thumbUrl有值，但是设置数据时候我分明是 NineGridBean nineGirdData = new NineGridBean(图片路径);，这个值设置的应该是originUrl啊

**Comment by 13938417646** [comment]
![1588149128(1)](https://user-images.githubusercontent.com/34367688/80576094-2eba0a00-8a37-11ea-9e5f-eefa2eaaeda7.jpg)

**Comment by Vanish136** [comment]
@13938417646 Sorry 传参的时候搞反了 1.4.1修复了这个
